// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models;

public enum PaymentType
{
    Pending, Credit, Debit
}

public partial class reservation
{
    public int Id { get; set; }

    public virtual guest guest { get; set; }

    public virtual card card { get; set; }

    public virtual Room room { get; set; }

    public int number_guest { get; set; }

    public double total_bill { get; set; }

    public PaymentType payment_type { get; set; }

    public DateTime arrival_time { get; set; }

    public DateTime leaving_time { get; set; }

    public bool check_in { get; set; }

    public int break_fast { get; set; }

    public int lunch { get; set; }

    public int dinner { get; set; }

    public bool cleaning { get; set; }

    public bool towel { get; set; }

    public bool s_surprise { get; set; }

    public bool supply_status { get; set; }

    public int food_bill { get; set; }
}