// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models;

public enum PaymentType
{
    Pending, Credit, Debit
}

public partial class reservation
{
    public int Id { get; set; }

    [ForeignKey("guest")]
    public long guestSSN { get; set; }
    public virtual guest guest { get; set; }

    [ForeignKey("card")]
    public int? cardId { get; set; } = null;
    public virtual card card { get; set; }

    [ForeignKey("room")]
    public int roomId { get; set; }
    public virtual Room room { get; set; }

    public int number_guest { get; set; }

    public decimal total_bill { get; set; }

    public PaymentType payment_type { get; set; }

    public DateTime arrival_time { get; set; }

    public DateTime leaving_time { get; set; }

    public bool check_in { get; set; }

    public int break_fast { get; set; }

    public int lunch { get; set; }

    public int dinner { get; set; }

    public bool cleaning { get; set; }

    public bool towel { get; set; }

    public bool s_surprise { get; set; }

    public bool supply_status { get; set; }

    public decimal food_bill { get; set; }
}